// <auto-generated />
// .NET 8.0.0
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Cometris.Boards
{
    public partial interface IMaskableBitBoard<TSelf, TLineElement, TVectorLineMask, TCompactLineMask>
    {
        #region Per-Line Operations

        #endregion
    }
}