// <auto-generated />
// .NET 8.0.10
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Cometris.Boards
{
    public readonly partial struct PartialBitBoard512
    {
        #region Vertical Shift
        #region Shift Down

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDownConstantLines(PartialBitBoard512 board, [ConstantExpected] int count, ushort upperFeedValue)
        {
            ArgumentOutOfRangeException.ThrowIfNegative(count);
            return (count) switch
            {
                0 => board,
                1 => ShiftDownOneLine(board, upperFeedValue),
                2 => ShiftDownTwoLines(board, upperFeedValue),
                3 => ShiftDownThreeLines(board, upperFeedValue),
                4 => ShiftDownFourLines(board, upperFeedValue),
                5 => ShiftDownFiveLines(board, upperFeedValue),
                6 => ShiftDownSixLines(board, upperFeedValue),
                7 => ShiftDownSevenLines(board, upperFeedValue),
                8 => ShiftDownEightLines(board, upperFeedValue),
                9 => ShiftDownNineLines(board, upperFeedValue),
                10 => ShiftDown10Lines(board, upperFeedValue),
                11 => ShiftDown11Lines(board, upperFeedValue),
                12 => ShiftDown12Lines(board, upperFeedValue),
                13 => ShiftDown13Lines(board, upperFeedValue),
                14 => ShiftDown14Lines(board, upperFeedValue),
                15 => ShiftDown15Lines(board, upperFeedValue),
                16 => ShiftDown16Lines(board, upperFeedValue),
                17 => ShiftDown17Lines(board, upperFeedValue),
                18 => ShiftDown18Lines(board, upperFeedValue),
                19 => ShiftDown19Lines(board, upperFeedValue),
                20 => ShiftDown20Lines(board, upperFeedValue),
                21 => ShiftDown21Lines(board, upperFeedValue),
                22 => ShiftDown22Lines(board, upperFeedValue),
                23 => ShiftDown23Lines(board, upperFeedValue),
                24 => ShiftDown24Lines(board, upperFeedValue),
                25 => ShiftDown25Lines(board, upperFeedValue),
                26 => ShiftDown26Lines(board, upperFeedValue),
                27 => ShiftDown27Lines(board, upperFeedValue),
                28 => ShiftDown28Lines(board, upperFeedValue),
                29 => ShiftDown29Lines(board, upperFeedValue),
                30 => ShiftDown30Lines(board, upperFeedValue),
                31 => ShiftDown31Lines(board, upperFeedValue),
                _ => new(upperFeedValue)
            };
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDownThreeLines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            var zmm2 = Avx512F.AlignRight32(zmm1.AsUInt32(), zmm0.AsUInt32(), 4).AsUInt16();
            return new(Avx512BW.AlignRight(zmm2.AsByte(), zmm0.AsByte(), 6).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDownFiveLines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            var zmm2 = Avx512F.AlignRight32(zmm1.AsUInt32(), zmm0.AsUInt32(), 4).AsUInt16();
            return new(Avx512BW.AlignRight(zmm2.AsByte(), zmm0.AsByte(), 10).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDownSixLines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm1 = Vector128.Create(upperFeedValue).ToVector256Unsafe().ToVector512Unsafe().AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm1, zmm0, 3).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDownSevenLines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            var zmm2 = Avx512F.AlignRight32(zmm1.AsUInt32(), zmm0.AsUInt32(), 4).AsUInt16();
            return new(Avx512BW.AlignRight(zmm2.AsByte(), zmm0.AsByte(), 14).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDownNineLines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm1, zmm0.AsUInt32(), 4).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm1.AsUInt32(), zmm0.AsUInt32(), 4).AsUInt16();
            return new(Avx512BW.AlignRight(zmm2.AsByte(), zmm0.AsByte(), 2).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown10Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm1, zmm0, 5).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown11Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm1, zmm0.AsUInt32(), 5).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm1.AsUInt32(), zmm0.AsUInt32(), 4).AsUInt16();
            return new(Avx512BW.AlignRight(zmm2.AsByte(), zmm0.AsByte(), 2).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown12Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm1, zmm0, 6).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown13Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm1, zmm0.AsUInt32(), 6).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm1.AsUInt32(), zmm0.AsUInt32(), 4).AsUInt16();
            return new(Avx512BW.AlignRight(zmm2.AsByte(), zmm0.AsByte(), 2).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown14Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm1, zmm0, 7).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown15Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm1, zmm0.AsUInt32(), 7).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm1.AsUInt32(), zmm0.AsUInt32(), 4).AsUInt16();
            return new(Avx512BW.AlignRight(zmm2.AsByte(), zmm0.AsByte(), 2).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown17Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm1, zmm0.AsUInt32(), 8).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm1.AsUInt32(), zmm0.AsUInt32(), 4).AsUInt16();
            return new(Avx512BW.AlignRight(zmm2.AsByte(), zmm0.AsByte(), 2).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown18Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm1, zmm0, 9).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown19Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm1, zmm0.AsUInt32(), 9).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm1.AsUInt32(), zmm0.AsUInt32(), 4).AsUInt16();
            return new(Avx512BW.AlignRight(zmm2.AsByte(), zmm0.AsByte(), 2).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown20Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm1, zmm0, 10).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown21Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm1, zmm0.AsUInt32(), 10).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm1.AsUInt32(), zmm0.AsUInt32(), 4).AsUInt16();
            return new(Avx512BW.AlignRight(zmm2.AsByte(), zmm0.AsByte(), 2).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown22Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm1, zmm0, 11).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown23Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm1, zmm0.AsUInt32(), 11).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm1.AsUInt32(), zmm0.AsUInt32(), 4).AsUInt16();
            return new(Avx512BW.AlignRight(zmm2.AsByte(), zmm0.AsByte(), 2).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown24Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm1, zmm0, 12).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown25Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm1, zmm0.AsUInt32(), 12).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm1.AsUInt32(), zmm0.AsUInt32(), 4).AsUInt16();
            return new(Avx512BW.AlignRight(zmm2.AsByte(), zmm0.AsByte(), 2).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown26Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm1, zmm0, 13).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown27Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm1, zmm0.AsUInt32(), 13).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm1.AsUInt32(), zmm0.AsUInt32(), 4).AsUInt16();
            return new(Avx512BW.AlignRight(zmm2.AsByte(), zmm0.AsByte(), 2).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown28Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm1, zmm0, 14).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown29Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm1, zmm0.AsUInt32(), 14).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm1.AsUInt32(), zmm0.AsUInt32(), 4).AsUInt16();
            return new(Avx512BW.AlignRight(zmm2.AsByte(), zmm0.AsByte(), 2).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown30Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm1, zmm0, 15).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftDown31Lines(PartialBitBoard512 board, ushort upperFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(upperFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm1, zmm0.AsUInt32(), 15).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm1.AsUInt32(), zmm0.AsUInt32(), 4).AsUInt16();
            return new(Avx512BW.AlignRight(zmm2.AsByte(), zmm0.AsByte(), 2).AsUInt16());
        }

        #endregion

        #region Shift Up

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUpConstantLines(PartialBitBoard512 board, [ConstantExpected] int count, ushort lowerFeedValue)
        {
            ArgumentOutOfRangeException.ThrowIfNegative(count);
            return (count) switch
            {
                0 => board,
                1 => ShiftUpOneLine(board, lowerFeedValue),
                2 => ShiftUpTwoLines(board, lowerFeedValue),
                3 => ShiftUpThreeLines(board, lowerFeedValue),
                4 => ShiftUpFourLines(board, lowerFeedValue),
                5 => ShiftUpFiveLines(board, lowerFeedValue),
                6 => ShiftUpSixLines(board, lowerFeedValue),
                7 => ShiftUpSevenLines(board, lowerFeedValue),
                8 => ShiftUpEightLines(board, lowerFeedValue),
                9 => ShiftUpNineLines(board, lowerFeedValue),
                10 => ShiftUp10Lines(board, lowerFeedValue),
                11 => ShiftUp11Lines(board, lowerFeedValue),
                12 => ShiftUp12Lines(board, lowerFeedValue),
                13 => ShiftUp13Lines(board, lowerFeedValue),
                14 => ShiftUp14Lines(board, lowerFeedValue),
                15 => ShiftUp15Lines(board, lowerFeedValue),
                16 => ShiftUp16Lines(board, lowerFeedValue),
                17 => ShiftUp17Lines(board, lowerFeedValue),
                18 => ShiftUp18Lines(board, lowerFeedValue),
                19 => ShiftUp19Lines(board, lowerFeedValue),
                20 => ShiftUp20Lines(board, lowerFeedValue),
                21 => ShiftUp21Lines(board, lowerFeedValue),
                22 => ShiftUp22Lines(board, lowerFeedValue),
                23 => ShiftUp23Lines(board, lowerFeedValue),
                24 => ShiftUp24Lines(board, lowerFeedValue),
                25 => ShiftUp25Lines(board, lowerFeedValue),
                26 => ShiftUp26Lines(board, lowerFeedValue),
                27 => ShiftUp27Lines(board, lowerFeedValue),
                28 => ShiftUp28Lines(board, lowerFeedValue),
                29 => ShiftUp29Lines(board, lowerFeedValue),
                30 => ShiftUp30Lines(board, lowerFeedValue),
                31 => ShiftUp31Lines(board, lowerFeedValue),
                _ => new(lowerFeedValue)
            };
        }
        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUpThreeLines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            var zmm2 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1.AsUInt32(), 12).AsUInt16();
            return new(Avx512BW.AlignRight(zmm0.AsByte(), zmm2.AsByte(), 10).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUpFiveLines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            var zmm2 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1.AsUInt32(), 12).AsUInt16();
            return new(Avx512BW.AlignRight(zmm0.AsByte(), zmm2.AsByte(), 6).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUpSixLines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm0, zmm1, 13).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUpSevenLines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            var zmm2 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1.AsUInt32(), 12).AsUInt16();
            return new(Avx512BW.AlignRight(zmm0.AsByte(), zmm2.AsByte(), 2).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUpNineLines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1, 12).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1.AsUInt32(), 12).AsUInt16();
            return new(Avx512BW.AlignRight(zmm0.AsByte(), zmm2.AsByte(), 14).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp10Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm0, zmm1, 11).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp11Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1, 11).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1.AsUInt32(), 12).AsUInt16();
            return new(Avx512BW.AlignRight(zmm0.AsByte(), zmm2.AsByte(), 14).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp12Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm0, zmm1, 10).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp13Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1, 10).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1.AsUInt32(), 12).AsUInt16();
            return new(Avx512BW.AlignRight(zmm0.AsByte(), zmm2.AsByte(), 14).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp14Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm0, zmm1, 9).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp15Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1, 9).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1.AsUInt32(), 12).AsUInt16();
            return new(Avx512BW.AlignRight(zmm0.AsByte(), zmm2.AsByte(), 14).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp17Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1, 8).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1.AsUInt32(), 12).AsUInt16();
            return new(Avx512BW.AlignRight(zmm0.AsByte(), zmm2.AsByte(), 14).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp18Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm0, zmm1, 7).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp19Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1, 7).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1.AsUInt32(), 12).AsUInt16();
            return new(Avx512BW.AlignRight(zmm0.AsByte(), zmm2.AsByte(), 14).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp20Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm0, zmm1, 6).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp21Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1, 6).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1.AsUInt32(), 12).AsUInt16();
            return new(Avx512BW.AlignRight(zmm0.AsByte(), zmm2.AsByte(), 14).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp22Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm0, zmm1, 5).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp23Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1, 5).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1.AsUInt32(), 12).AsUInt16();
            return new(Avx512BW.AlignRight(zmm0.AsByte(), zmm2.AsByte(), 14).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp24Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm0, zmm1, 4).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp25Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1, 4).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1.AsUInt32(), 12).AsUInt16();
            return new(Avx512BW.AlignRight(zmm0.AsByte(), zmm2.AsByte(), 14).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp26Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm0, zmm1, 3).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp27Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1, 3).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1.AsUInt32(), 12).AsUInt16();
            return new(Avx512BW.AlignRight(zmm0.AsByte(), zmm2.AsByte(), 14).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp28Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm0, zmm1, 2).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp29Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1, 2).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1.AsUInt32(), 12).AsUInt16();
            return new(Avx512BW.AlignRight(zmm0.AsByte(), zmm2.AsByte(), 14).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp30Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            var zmm0 = board.storage.AsUInt32();
            return new(Avx512F.AlignRight32(zmm0, zmm1, 1).AsUInt16());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
        public static PartialBitBoard512 ShiftUp31Lines(PartialBitBoard512 board, ushort lowerFeedValue)
        {
            var zmm0 = board.storage;
            var zmm1 = Vector512.Create(lowerFeedValue).AsUInt32();
            zmm0 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1, 1).AsUInt16();
            var zmm2 = Avx512F.AlignRight32(zmm0.AsUInt32(), zmm1.AsUInt32(), 12).AsUInt16();
            return new(Avx512BW.AlignRight(zmm0.AsByte(), zmm2.AsByte(), 14).AsUInt16());
        }

        #endregion
        #endregion
    }
}