// <auto-generated />
// .NET 9.0.0
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Cometris.Utils.Vector
{
    public readonly partial struct QuadVector128<T> where T : unmanaged
    {
        #region Operator Overloads
        public static QuadVector128<T> operator &(QuadVector128<T> left, QuadVector128<T> right)
            => new(left.V0 & right.V0, left.V1 & right.V1, left.V2 & right.V2, left.V3 & right.V3);
        
        public static QuadVector128<T> operator &(Vector128<T> left, QuadVector128<T> right)
            => new(left & right.V0, left & right.V1, left & right.V2, left & right.V3);
        
        public static QuadVector128<T> operator &(QuadVector128<T> left, Vector128<T> right)
            => new(left.V0 & right, left.V1 & right, left.V2 & right, left.V3 & right);
        
        public static QuadVector128<T> operator |(QuadVector128<T> left, QuadVector128<T> right)
            => new(left.V0 | right.V0, left.V1 | right.V1, left.V2 | right.V2, left.V3 | right.V3);
        
        public static QuadVector128<T> operator |(Vector128<T> left, QuadVector128<T> right)
            => new(left | right.V0, left | right.V1, left | right.V2, left | right.V3);
        
        public static QuadVector128<T> operator |(QuadVector128<T> left, Vector128<T> right)
            => new(left.V0 | right, left.V1 | right, left.V2 | right, left.V3 | right);
        
        public static QuadVector128<T> operator ^(QuadVector128<T> left, QuadVector128<T> right)
            => new(left.V0 ^ right.V0, left.V1 ^ right.V1, left.V2 ^ right.V2, left.V3 ^ right.V3);
        
        public static QuadVector128<T> operator ^(Vector128<T> left, QuadVector128<T> right)
            => new(left ^ right.V0, left ^ right.V1, left ^ right.V2, left ^ right.V3);
        
        public static QuadVector128<T> operator ^(QuadVector128<T> left, Vector128<T> right)
            => new(left.V0 ^ right, left.V1 ^ right, left.V2 ^ right, left.V3 ^ right);
        
        public static QuadVector128<T> operator +(QuadVector128<T> left, QuadVector128<T> right)
            => new(left.V0 + right.V0, left.V1 + right.V1, left.V2 + right.V2, left.V3 + right.V3);
        
        public static QuadVector128<T> operator +(Vector128<T> left, QuadVector128<T> right)
            => new(left + right.V0, left + right.V1, left + right.V2, left + right.V3);
        
        public static QuadVector128<T> operator +(QuadVector128<T> left, Vector128<T> right)
            => new(left.V0 + right, left.V1 + right, left.V2 + right, left.V3 + right);
        
        public static QuadVector128<T> operator -(QuadVector128<T> left, QuadVector128<T> right)
            => new(left.V0 - right.V0, left.V1 - right.V1, left.V2 - right.V2, left.V3 - right.V3);
        
        public static QuadVector128<T> operator -(Vector128<T> left, QuadVector128<T> right)
            => new(left - right.V0, left - right.V1, left - right.V2, left - right.V3);
        
        public static QuadVector128<T> operator -(QuadVector128<T> left, Vector128<T> right)
            => new(left.V0 - right, left.V1 - right, left.V2 - right, left.V3 - right);
        
        public static QuadVector128<T> operator *(QuadVector128<T> left, QuadVector128<T> right)
            => new(left.V0 * right.V0, left.V1 * right.V1, left.V2 * right.V2, left.V3 * right.V3);
        
        public static QuadVector128<T> operator *(Vector128<T> left, QuadVector128<T> right)
            => new(left * right.V0, left * right.V1, left * right.V2, left * right.V3);
        
        public static QuadVector128<T> operator *(QuadVector128<T> left, Vector128<T> right)
            => new(left.V0 * right, left.V1 * right, left.V2 * right, left.V3 * right);
        
        public static QuadVector128<T> operator /(QuadVector128<T> left, QuadVector128<T> right)
            => new(left.V0 / right.V0, left.V1 / right.V1, left.V2 / right.V2, left.V3 / right.V3);
        
        public static QuadVector128<T> operator /(Vector128<T> left, QuadVector128<T> right)
            => new(left / right.V0, left / right.V1, left / right.V2, left / right.V3);
        
        public static QuadVector128<T> operator /(QuadVector128<T> left, Vector128<T> right)
            => new(left.V0 / right, left.V1 / right, left.V2 / right, left.V3 / right);
        
        public static QuadVector128<T> operator <<(QuadVector128<T> left, [ConstantExpected] int right)
            => new(left.V0 << right, left.V1 << right, left.V2 << right, left.V3 << right);
        
        public static QuadVector128<T> operator >>(QuadVector128<T> left, [ConstantExpected] int right)
            => new(left.V0 >> right, left.V1 >> right, left.V2 >> right, left.V3 >> right);
        
        public static QuadVector128<T> operator ~(QuadVector128<T> value)
            => new(~value.V0, ~value.V1, ~value.V2, ~value.V3);
        #endregion
    }

    public static partial class QuadVector128
    {
        /// <returns>mask ? left : right</returns>
        public static QuadVector128<T> ConditionalSelect<T>(QuadVector128<T> mask, QuadVector128<T> left, QuadVector128<T> right) where T : unmanaged
            => new(Vector128.ConditionalSelect(mask.V0, left.V0, right.V0), Vector128.ConditionalSelect(mask.V1, left.V1, right.V1), Vector128.ConditionalSelect(mask.V2, left.V2, right.V2), Vector128.ConditionalSelect(mask.V3, left.V3, right.V3));

        public static QuadVector128<T> CompareEqual<T>(QuadVector128<T> left, QuadVector128<T> right) where T : unmanaged
            => new(Vector128.Equals(left.V0, right.V0), Vector128.Equals(left.V1, right.V1), Vector128.Equals(left.V2, right.V2), Vector128.Equals(left.V3, right.V3));

        public static QuadVector128<byte> ShuffleBytesPerLane(QuadVector128<byte> tables, QuadVector128<byte> indices)
            => new(VectorUtils.VectorTableLookup(tables.V0, indices.V0), VectorUtils.VectorTableLookup(tables.V1, indices.V1), VectorUtils.VectorTableLookup(tables.V2, indices.V2), VectorUtils.VectorTableLookup(tables.V3, indices.V3));

        public static QuadVector128<byte> ShuffleBytesPerLane(QuadVector128<byte> tables, Vector128<byte> indices)
            => new(VectorUtils.VectorTableLookup(tables.V0, indices), VectorUtils.VectorTableLookup(tables.V1, indices), VectorUtils.VectorTableLookup(tables.V2, indices), VectorUtils.VectorTableLookup(tables.V3, indices));

        public static QuadVector128<byte> ShuffleBytesPerLane(Vector128<byte> table, QuadVector128<byte> indices)
            => new(VectorUtils.VectorTableLookup(table, indices.V0), VectorUtils.VectorTableLookup(table, indices.V1), VectorUtils.VectorTableLookup(table, indices.V2), VectorUtils.VectorTableLookup(table, indices.V3));

        public static QuadVector128<TTo> As<TFrom, TTo>(this QuadVector128<TFrom> vector) where TFrom : unmanaged where TTo : unmanaged
            => new(Vector128.As<TFrom, TTo>(vector.V0), Vector128.As<TFrom, TTo>(vector.V1), Vector128.As<TFrom, TTo>(vector.V2), Vector128.As<TFrom, TTo>(vector.V3));

        public static QuadVector128<T> BroadcastFirstElementPerLane<T>(this QuadVector128<T> vector) where T : unmanaged
            => new(VectorUtils.BroadcastFirstElement(vector.V0), VectorUtils.BroadcastFirstElement(vector.V1), VectorUtils.BroadcastFirstElement(vector.V2), VectorUtils.BroadcastFirstElement(vector.V3));
        

        public static QuadVector128<byte> AsByte<T>(this QuadVector128<T> vector) where T : unmanaged
            => new(Vector128.As<T, byte>(vector.V0), Vector128.As<T, byte>(vector.V1), Vector128.As<T, byte>(vector.V2), Vector128.As<T, byte>(vector.V3));

        public static QuadVector128<sbyte> AsSByte<T>(this QuadVector128<T> vector) where T : unmanaged
            => new(Vector128.As<T, sbyte>(vector.V0), Vector128.As<T, sbyte>(vector.V1), Vector128.As<T, sbyte>(vector.V2), Vector128.As<T, sbyte>(vector.V3));

        public static QuadVector128<ushort> AsUInt16<T>(this QuadVector128<T> vector) where T : unmanaged
            => new(Vector128.As<T, ushort>(vector.V0), Vector128.As<T, ushort>(vector.V1), Vector128.As<T, ushort>(vector.V2), Vector128.As<T, ushort>(vector.V3));

        public static QuadVector128<short> AsInt16<T>(this QuadVector128<T> vector) where T : unmanaged
            => new(Vector128.As<T, short>(vector.V0), Vector128.As<T, short>(vector.V1), Vector128.As<T, short>(vector.V2), Vector128.As<T, short>(vector.V3));

        public static QuadVector128<uint> AsUInt32<T>(this QuadVector128<T> vector) where T : unmanaged
            => new(Vector128.As<T, uint>(vector.V0), Vector128.As<T, uint>(vector.V1), Vector128.As<T, uint>(vector.V2), Vector128.As<T, uint>(vector.V3));

        public static QuadVector128<int> AsInt32<T>(this QuadVector128<T> vector) where T : unmanaged
            => new(Vector128.As<T, int>(vector.V0), Vector128.As<T, int>(vector.V1), Vector128.As<T, int>(vector.V2), Vector128.As<T, int>(vector.V3));

        public static QuadVector128<float> AsSingle<T>(this QuadVector128<T> vector) where T : unmanaged
            => new(Vector128.As<T, float>(vector.V0), Vector128.As<T, float>(vector.V1), Vector128.As<T, float>(vector.V2), Vector128.As<T, float>(vector.V3));

        public static QuadVector128<ulong> AsUInt64<T>(this QuadVector128<T> vector) where T : unmanaged
            => new(Vector128.As<T, ulong>(vector.V0), Vector128.As<T, ulong>(vector.V1), Vector128.As<T, ulong>(vector.V2), Vector128.As<T, ulong>(vector.V3));

        public static QuadVector128<long> AsInt64<T>(this QuadVector128<T> vector) where T : unmanaged
            => new(Vector128.As<T, long>(vector.V0), Vector128.As<T, long>(vector.V1), Vector128.As<T, long>(vector.V2), Vector128.As<T, long>(vector.V3));

        public static QuadVector128<double> AsDouble<T>(this QuadVector128<T> vector) where T : unmanaged
            => new(Vector128.As<T, double>(vector.V0), Vector128.As<T, double>(vector.V1), Vector128.As<T, double>(vector.V2), Vector128.As<T, double>(vector.V3));

        public static QuadVector128<byte> CompareGreaterThan(QuadVector128<byte> left, QuadVector128<byte> right)
            => new(Vector128.GreaterThan(left.V0, right.V0), Vector128.GreaterThan(left.V1, right.V1), Vector128.GreaterThan(left.V2, right.V2), Vector128.GreaterThan(left.V3, right.V3));

        public static QuadVector128<byte> CompareGreaterThan(QuadVector128<byte> left, Vector128<byte> right)
            => new(Vector128.GreaterThan(left.V0, right), Vector128.GreaterThan(left.V1, right), Vector128.GreaterThan(left.V2, right), Vector128.GreaterThan(left.V3, right));

        public static QuadVector128<byte> CompareGreaterThan(Vector128<byte> left, QuadVector128<byte> right)
            => new(Vector128.GreaterThan(left, right.V0), Vector128.GreaterThan(left, right.V1), Vector128.GreaterThan(left, right.V2), Vector128.GreaterThan(left, right.V3));

        public static QuadVector128<sbyte> CompareGreaterThan(QuadVector128<sbyte> left, QuadVector128<sbyte> right)
            => new(Vector128.GreaterThan(left.V0, right.V0), Vector128.GreaterThan(left.V1, right.V1), Vector128.GreaterThan(left.V2, right.V2), Vector128.GreaterThan(left.V3, right.V3));

        public static QuadVector128<sbyte> CompareGreaterThan(QuadVector128<sbyte> left, Vector128<sbyte> right)
            => new(Vector128.GreaterThan(left.V0, right), Vector128.GreaterThan(left.V1, right), Vector128.GreaterThan(left.V2, right), Vector128.GreaterThan(left.V3, right));

        public static QuadVector128<sbyte> CompareGreaterThan(Vector128<sbyte> left, QuadVector128<sbyte> right)
            => new(Vector128.GreaterThan(left, right.V0), Vector128.GreaterThan(left, right.V1), Vector128.GreaterThan(left, right.V2), Vector128.GreaterThan(left, right.V3));

        public static QuadVector128<ushort> CompareGreaterThan(QuadVector128<ushort> left, QuadVector128<ushort> right)
            => new(Vector128.GreaterThan(left.V0, right.V0), Vector128.GreaterThan(left.V1, right.V1), Vector128.GreaterThan(left.V2, right.V2), Vector128.GreaterThan(left.V3, right.V3));

        public static QuadVector128<ushort> CompareGreaterThan(QuadVector128<ushort> left, Vector128<ushort> right)
            => new(Vector128.GreaterThan(left.V0, right), Vector128.GreaterThan(left.V1, right), Vector128.GreaterThan(left.V2, right), Vector128.GreaterThan(left.V3, right));

        public static QuadVector128<ushort> CompareGreaterThan(Vector128<ushort> left, QuadVector128<ushort> right)
            => new(Vector128.GreaterThan(left, right.V0), Vector128.GreaterThan(left, right.V1), Vector128.GreaterThan(left, right.V2), Vector128.GreaterThan(left, right.V3));

        public static QuadVector128<short> CompareGreaterThan(QuadVector128<short> left, QuadVector128<short> right)
            => new(Vector128.GreaterThan(left.V0, right.V0), Vector128.GreaterThan(left.V1, right.V1), Vector128.GreaterThan(left.V2, right.V2), Vector128.GreaterThan(left.V3, right.V3));

        public static QuadVector128<short> CompareGreaterThan(QuadVector128<short> left, Vector128<short> right)
            => new(Vector128.GreaterThan(left.V0, right), Vector128.GreaterThan(left.V1, right), Vector128.GreaterThan(left.V2, right), Vector128.GreaterThan(left.V3, right));

        public static QuadVector128<short> CompareGreaterThan(Vector128<short> left, QuadVector128<short> right)
            => new(Vector128.GreaterThan(left, right.V0), Vector128.GreaterThan(left, right.V1), Vector128.GreaterThan(left, right.V2), Vector128.GreaterThan(left, right.V3));

        public static QuadVector128<uint> CompareGreaterThan(QuadVector128<uint> left, QuadVector128<uint> right)
            => new(Vector128.GreaterThan(left.V0, right.V0), Vector128.GreaterThan(left.V1, right.V1), Vector128.GreaterThan(left.V2, right.V2), Vector128.GreaterThan(left.V3, right.V3));

        public static QuadVector128<uint> CompareGreaterThan(QuadVector128<uint> left, Vector128<uint> right)
            => new(Vector128.GreaterThan(left.V0, right), Vector128.GreaterThan(left.V1, right), Vector128.GreaterThan(left.V2, right), Vector128.GreaterThan(left.V3, right));

        public static QuadVector128<uint> CompareGreaterThan(Vector128<uint> left, QuadVector128<uint> right)
            => new(Vector128.GreaterThan(left, right.V0), Vector128.GreaterThan(left, right.V1), Vector128.GreaterThan(left, right.V2), Vector128.GreaterThan(left, right.V3));

        public static QuadVector128<int> CompareGreaterThan(QuadVector128<int> left, QuadVector128<int> right)
            => new(Vector128.GreaterThan(left.V0, right.V0), Vector128.GreaterThan(left.V1, right.V1), Vector128.GreaterThan(left.V2, right.V2), Vector128.GreaterThan(left.V3, right.V3));

        public static QuadVector128<int> CompareGreaterThan(QuadVector128<int> left, Vector128<int> right)
            => new(Vector128.GreaterThan(left.V0, right), Vector128.GreaterThan(left.V1, right), Vector128.GreaterThan(left.V2, right), Vector128.GreaterThan(left.V3, right));

        public static QuadVector128<int> CompareGreaterThan(Vector128<int> left, QuadVector128<int> right)
            => new(Vector128.GreaterThan(left, right.V0), Vector128.GreaterThan(left, right.V1), Vector128.GreaterThan(left, right.V2), Vector128.GreaterThan(left, right.V3));

        public static QuadVector128<float> CompareGreaterThan(QuadVector128<float> left, QuadVector128<float> right)
            => new(Vector128.GreaterThan(left.V0, right.V0), Vector128.GreaterThan(left.V1, right.V1), Vector128.GreaterThan(left.V2, right.V2), Vector128.GreaterThan(left.V3, right.V3));

        public static QuadVector128<float> CompareGreaterThan(QuadVector128<float> left, Vector128<float> right)
            => new(Vector128.GreaterThan(left.V0, right), Vector128.GreaterThan(left.V1, right), Vector128.GreaterThan(left.V2, right), Vector128.GreaterThan(left.V3, right));

        public static QuadVector128<float> CompareGreaterThan(Vector128<float> left, QuadVector128<float> right)
            => new(Vector128.GreaterThan(left, right.V0), Vector128.GreaterThan(left, right.V1), Vector128.GreaterThan(left, right.V2), Vector128.GreaterThan(left, right.V3));

        public static QuadVector128<ulong> CompareGreaterThan(QuadVector128<ulong> left, QuadVector128<ulong> right)
            => new(Vector128.GreaterThan(left.V0, right.V0), Vector128.GreaterThan(left.V1, right.V1), Vector128.GreaterThan(left.V2, right.V2), Vector128.GreaterThan(left.V3, right.V3));

        public static QuadVector128<ulong> CompareGreaterThan(QuadVector128<ulong> left, Vector128<ulong> right)
            => new(Vector128.GreaterThan(left.V0, right), Vector128.GreaterThan(left.V1, right), Vector128.GreaterThan(left.V2, right), Vector128.GreaterThan(left.V3, right));

        public static QuadVector128<ulong> CompareGreaterThan(Vector128<ulong> left, QuadVector128<ulong> right)
            => new(Vector128.GreaterThan(left, right.V0), Vector128.GreaterThan(left, right.V1), Vector128.GreaterThan(left, right.V2), Vector128.GreaterThan(left, right.V3));

        public static QuadVector128<long> CompareGreaterThan(QuadVector128<long> left, QuadVector128<long> right)
            => new(Vector128.GreaterThan(left.V0, right.V0), Vector128.GreaterThan(left.V1, right.V1), Vector128.GreaterThan(left.V2, right.V2), Vector128.GreaterThan(left.V3, right.V3));

        public static QuadVector128<long> CompareGreaterThan(QuadVector128<long> left, Vector128<long> right)
            => new(Vector128.GreaterThan(left.V0, right), Vector128.GreaterThan(left.V1, right), Vector128.GreaterThan(left.V2, right), Vector128.GreaterThan(left.V3, right));

        public static QuadVector128<long> CompareGreaterThan(Vector128<long> left, QuadVector128<long> right)
            => new(Vector128.GreaterThan(left, right.V0), Vector128.GreaterThan(left, right.V1), Vector128.GreaterThan(left, right.V2), Vector128.GreaterThan(left, right.V3));

        public static QuadVector128<double> CompareGreaterThan(QuadVector128<double> left, QuadVector128<double> right)
            => new(Vector128.GreaterThan(left.V0, right.V0), Vector128.GreaterThan(left.V1, right.V1), Vector128.GreaterThan(left.V2, right.V2), Vector128.GreaterThan(left.V3, right.V3));

        public static QuadVector128<double> CompareGreaterThan(QuadVector128<double> left, Vector128<double> right)
            => new(Vector128.GreaterThan(left.V0, right), Vector128.GreaterThan(left.V1, right), Vector128.GreaterThan(left.V2, right), Vector128.GreaterThan(left.V3, right));

        public static QuadVector128<double> CompareGreaterThan(Vector128<double> left, QuadVector128<double> right)
            => new(Vector128.GreaterThan(left, right.V0), Vector128.GreaterThan(left, right.V1), Vector128.GreaterThan(left, right.V2), Vector128.GreaterThan(left, right.V3));

        public static QuadVector128<byte> CompareGreaterThanOrEqual(QuadVector128<byte> left, QuadVector128<byte> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right.V0), Vector128.GreaterThanOrEqual(left.V1, right.V1), Vector128.GreaterThanOrEqual(left.V2, right.V2), Vector128.GreaterThanOrEqual(left.V3, right.V3));

        public static QuadVector128<byte> CompareGreaterThanOrEqual(QuadVector128<byte> left, Vector128<byte> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right), Vector128.GreaterThanOrEqual(left.V1, right), Vector128.GreaterThanOrEqual(left.V2, right), Vector128.GreaterThanOrEqual(left.V3, right));

        public static QuadVector128<byte> CompareGreaterThanOrEqual(Vector128<byte> left, QuadVector128<byte> right)
            => new(Vector128.GreaterThanOrEqual(left, right.V0), Vector128.GreaterThanOrEqual(left, right.V1), Vector128.GreaterThanOrEqual(left, right.V2), Vector128.GreaterThanOrEqual(left, right.V3));

        public static QuadVector128<sbyte> CompareGreaterThanOrEqual(QuadVector128<sbyte> left, QuadVector128<sbyte> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right.V0), Vector128.GreaterThanOrEqual(left.V1, right.V1), Vector128.GreaterThanOrEqual(left.V2, right.V2), Vector128.GreaterThanOrEqual(left.V3, right.V3));

        public static QuadVector128<sbyte> CompareGreaterThanOrEqual(QuadVector128<sbyte> left, Vector128<sbyte> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right), Vector128.GreaterThanOrEqual(left.V1, right), Vector128.GreaterThanOrEqual(left.V2, right), Vector128.GreaterThanOrEqual(left.V3, right));

        public static QuadVector128<sbyte> CompareGreaterThanOrEqual(Vector128<sbyte> left, QuadVector128<sbyte> right)
            => new(Vector128.GreaterThanOrEqual(left, right.V0), Vector128.GreaterThanOrEqual(left, right.V1), Vector128.GreaterThanOrEqual(left, right.V2), Vector128.GreaterThanOrEqual(left, right.V3));

        public static QuadVector128<ushort> CompareGreaterThanOrEqual(QuadVector128<ushort> left, QuadVector128<ushort> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right.V0), Vector128.GreaterThanOrEqual(left.V1, right.V1), Vector128.GreaterThanOrEqual(left.V2, right.V2), Vector128.GreaterThanOrEqual(left.V3, right.V3));

        public static QuadVector128<ushort> CompareGreaterThanOrEqual(QuadVector128<ushort> left, Vector128<ushort> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right), Vector128.GreaterThanOrEqual(left.V1, right), Vector128.GreaterThanOrEqual(left.V2, right), Vector128.GreaterThanOrEqual(left.V3, right));

        public static QuadVector128<ushort> CompareGreaterThanOrEqual(Vector128<ushort> left, QuadVector128<ushort> right)
            => new(Vector128.GreaterThanOrEqual(left, right.V0), Vector128.GreaterThanOrEqual(left, right.V1), Vector128.GreaterThanOrEqual(left, right.V2), Vector128.GreaterThanOrEqual(left, right.V3));

        public static QuadVector128<short> CompareGreaterThanOrEqual(QuadVector128<short> left, QuadVector128<short> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right.V0), Vector128.GreaterThanOrEqual(left.V1, right.V1), Vector128.GreaterThanOrEqual(left.V2, right.V2), Vector128.GreaterThanOrEqual(left.V3, right.V3));

        public static QuadVector128<short> CompareGreaterThanOrEqual(QuadVector128<short> left, Vector128<short> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right), Vector128.GreaterThanOrEqual(left.V1, right), Vector128.GreaterThanOrEqual(left.V2, right), Vector128.GreaterThanOrEqual(left.V3, right));

        public static QuadVector128<short> CompareGreaterThanOrEqual(Vector128<short> left, QuadVector128<short> right)
            => new(Vector128.GreaterThanOrEqual(left, right.V0), Vector128.GreaterThanOrEqual(left, right.V1), Vector128.GreaterThanOrEqual(left, right.V2), Vector128.GreaterThanOrEqual(left, right.V3));

        public static QuadVector128<uint> CompareGreaterThanOrEqual(QuadVector128<uint> left, QuadVector128<uint> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right.V0), Vector128.GreaterThanOrEqual(left.V1, right.V1), Vector128.GreaterThanOrEqual(left.V2, right.V2), Vector128.GreaterThanOrEqual(left.V3, right.V3));

        public static QuadVector128<uint> CompareGreaterThanOrEqual(QuadVector128<uint> left, Vector128<uint> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right), Vector128.GreaterThanOrEqual(left.V1, right), Vector128.GreaterThanOrEqual(left.V2, right), Vector128.GreaterThanOrEqual(left.V3, right));

        public static QuadVector128<uint> CompareGreaterThanOrEqual(Vector128<uint> left, QuadVector128<uint> right)
            => new(Vector128.GreaterThanOrEqual(left, right.V0), Vector128.GreaterThanOrEqual(left, right.V1), Vector128.GreaterThanOrEqual(left, right.V2), Vector128.GreaterThanOrEqual(left, right.V3));

        public static QuadVector128<int> CompareGreaterThanOrEqual(QuadVector128<int> left, QuadVector128<int> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right.V0), Vector128.GreaterThanOrEqual(left.V1, right.V1), Vector128.GreaterThanOrEqual(left.V2, right.V2), Vector128.GreaterThanOrEqual(left.V3, right.V3));

        public static QuadVector128<int> CompareGreaterThanOrEqual(QuadVector128<int> left, Vector128<int> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right), Vector128.GreaterThanOrEqual(left.V1, right), Vector128.GreaterThanOrEqual(left.V2, right), Vector128.GreaterThanOrEqual(left.V3, right));

        public static QuadVector128<int> CompareGreaterThanOrEqual(Vector128<int> left, QuadVector128<int> right)
            => new(Vector128.GreaterThanOrEqual(left, right.V0), Vector128.GreaterThanOrEqual(left, right.V1), Vector128.GreaterThanOrEqual(left, right.V2), Vector128.GreaterThanOrEqual(left, right.V3));

        public static QuadVector128<float> CompareGreaterThanOrEqual(QuadVector128<float> left, QuadVector128<float> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right.V0), Vector128.GreaterThanOrEqual(left.V1, right.V1), Vector128.GreaterThanOrEqual(left.V2, right.V2), Vector128.GreaterThanOrEqual(left.V3, right.V3));

        public static QuadVector128<float> CompareGreaterThanOrEqual(QuadVector128<float> left, Vector128<float> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right), Vector128.GreaterThanOrEqual(left.V1, right), Vector128.GreaterThanOrEqual(left.V2, right), Vector128.GreaterThanOrEqual(left.V3, right));

        public static QuadVector128<float> CompareGreaterThanOrEqual(Vector128<float> left, QuadVector128<float> right)
            => new(Vector128.GreaterThanOrEqual(left, right.V0), Vector128.GreaterThanOrEqual(left, right.V1), Vector128.GreaterThanOrEqual(left, right.V2), Vector128.GreaterThanOrEqual(left, right.V3));

        public static QuadVector128<ulong> CompareGreaterThanOrEqual(QuadVector128<ulong> left, QuadVector128<ulong> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right.V0), Vector128.GreaterThanOrEqual(left.V1, right.V1), Vector128.GreaterThanOrEqual(left.V2, right.V2), Vector128.GreaterThanOrEqual(left.V3, right.V3));

        public static QuadVector128<ulong> CompareGreaterThanOrEqual(QuadVector128<ulong> left, Vector128<ulong> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right), Vector128.GreaterThanOrEqual(left.V1, right), Vector128.GreaterThanOrEqual(left.V2, right), Vector128.GreaterThanOrEqual(left.V3, right));

        public static QuadVector128<ulong> CompareGreaterThanOrEqual(Vector128<ulong> left, QuadVector128<ulong> right)
            => new(Vector128.GreaterThanOrEqual(left, right.V0), Vector128.GreaterThanOrEqual(left, right.V1), Vector128.GreaterThanOrEqual(left, right.V2), Vector128.GreaterThanOrEqual(left, right.V3));

        public static QuadVector128<long> CompareGreaterThanOrEqual(QuadVector128<long> left, QuadVector128<long> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right.V0), Vector128.GreaterThanOrEqual(left.V1, right.V1), Vector128.GreaterThanOrEqual(left.V2, right.V2), Vector128.GreaterThanOrEqual(left.V3, right.V3));

        public static QuadVector128<long> CompareGreaterThanOrEqual(QuadVector128<long> left, Vector128<long> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right), Vector128.GreaterThanOrEqual(left.V1, right), Vector128.GreaterThanOrEqual(left.V2, right), Vector128.GreaterThanOrEqual(left.V3, right));

        public static QuadVector128<long> CompareGreaterThanOrEqual(Vector128<long> left, QuadVector128<long> right)
            => new(Vector128.GreaterThanOrEqual(left, right.V0), Vector128.GreaterThanOrEqual(left, right.V1), Vector128.GreaterThanOrEqual(left, right.V2), Vector128.GreaterThanOrEqual(left, right.V3));

        public static QuadVector128<double> CompareGreaterThanOrEqual(QuadVector128<double> left, QuadVector128<double> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right.V0), Vector128.GreaterThanOrEqual(left.V1, right.V1), Vector128.GreaterThanOrEqual(left.V2, right.V2), Vector128.GreaterThanOrEqual(left.V3, right.V3));

        public static QuadVector128<double> CompareGreaterThanOrEqual(QuadVector128<double> left, Vector128<double> right)
            => new(Vector128.GreaterThanOrEqual(left.V0, right), Vector128.GreaterThanOrEqual(left.V1, right), Vector128.GreaterThanOrEqual(left.V2, right), Vector128.GreaterThanOrEqual(left.V3, right));

        public static QuadVector128<double> CompareGreaterThanOrEqual(Vector128<double> left, QuadVector128<double> right)
            => new(Vector128.GreaterThanOrEqual(left, right.V0), Vector128.GreaterThanOrEqual(left, right.V1), Vector128.GreaterThanOrEqual(left, right.V2), Vector128.GreaterThanOrEqual(left, right.V3));

        public static QuadVector128<byte> CompareLessThan(QuadVector128<byte> left, QuadVector128<byte> right)
            => new(Vector128.LessThan(left.V0, right.V0), Vector128.LessThan(left.V1, right.V1), Vector128.LessThan(left.V2, right.V2), Vector128.LessThan(left.V3, right.V3));

        public static QuadVector128<byte> CompareLessThan(QuadVector128<byte> left, Vector128<byte> right)
            => new(Vector128.LessThan(left.V0, right), Vector128.LessThan(left.V1, right), Vector128.LessThan(left.V2, right), Vector128.LessThan(left.V3, right));

        public static QuadVector128<byte> CompareLessThan(Vector128<byte> left, QuadVector128<byte> right)
            => new(Vector128.LessThan(left, right.V0), Vector128.LessThan(left, right.V1), Vector128.LessThan(left, right.V2), Vector128.LessThan(left, right.V3));

        public static QuadVector128<sbyte> CompareLessThan(QuadVector128<sbyte> left, QuadVector128<sbyte> right)
            => new(Vector128.LessThan(left.V0, right.V0), Vector128.LessThan(left.V1, right.V1), Vector128.LessThan(left.V2, right.V2), Vector128.LessThan(left.V3, right.V3));

        public static QuadVector128<sbyte> CompareLessThan(QuadVector128<sbyte> left, Vector128<sbyte> right)
            => new(Vector128.LessThan(left.V0, right), Vector128.LessThan(left.V1, right), Vector128.LessThan(left.V2, right), Vector128.LessThan(left.V3, right));

        public static QuadVector128<sbyte> CompareLessThan(Vector128<sbyte> left, QuadVector128<sbyte> right)
            => new(Vector128.LessThan(left, right.V0), Vector128.LessThan(left, right.V1), Vector128.LessThan(left, right.V2), Vector128.LessThan(left, right.V3));

        public static QuadVector128<ushort> CompareLessThan(QuadVector128<ushort> left, QuadVector128<ushort> right)
            => new(Vector128.LessThan(left.V0, right.V0), Vector128.LessThan(left.V1, right.V1), Vector128.LessThan(left.V2, right.V2), Vector128.LessThan(left.V3, right.V3));

        public static QuadVector128<ushort> CompareLessThan(QuadVector128<ushort> left, Vector128<ushort> right)
            => new(Vector128.LessThan(left.V0, right), Vector128.LessThan(left.V1, right), Vector128.LessThan(left.V2, right), Vector128.LessThan(left.V3, right));

        public static QuadVector128<ushort> CompareLessThan(Vector128<ushort> left, QuadVector128<ushort> right)
            => new(Vector128.LessThan(left, right.V0), Vector128.LessThan(left, right.V1), Vector128.LessThan(left, right.V2), Vector128.LessThan(left, right.V3));

        public static QuadVector128<short> CompareLessThan(QuadVector128<short> left, QuadVector128<short> right)
            => new(Vector128.LessThan(left.V0, right.V0), Vector128.LessThan(left.V1, right.V1), Vector128.LessThan(left.V2, right.V2), Vector128.LessThan(left.V3, right.V3));

        public static QuadVector128<short> CompareLessThan(QuadVector128<short> left, Vector128<short> right)
            => new(Vector128.LessThan(left.V0, right), Vector128.LessThan(left.V1, right), Vector128.LessThan(left.V2, right), Vector128.LessThan(left.V3, right));

        public static QuadVector128<short> CompareLessThan(Vector128<short> left, QuadVector128<short> right)
            => new(Vector128.LessThan(left, right.V0), Vector128.LessThan(left, right.V1), Vector128.LessThan(left, right.V2), Vector128.LessThan(left, right.V3));

        public static QuadVector128<uint> CompareLessThan(QuadVector128<uint> left, QuadVector128<uint> right)
            => new(Vector128.LessThan(left.V0, right.V0), Vector128.LessThan(left.V1, right.V1), Vector128.LessThan(left.V2, right.V2), Vector128.LessThan(left.V3, right.V3));

        public static QuadVector128<uint> CompareLessThan(QuadVector128<uint> left, Vector128<uint> right)
            => new(Vector128.LessThan(left.V0, right), Vector128.LessThan(left.V1, right), Vector128.LessThan(left.V2, right), Vector128.LessThan(left.V3, right));

        public static QuadVector128<uint> CompareLessThan(Vector128<uint> left, QuadVector128<uint> right)
            => new(Vector128.LessThan(left, right.V0), Vector128.LessThan(left, right.V1), Vector128.LessThan(left, right.V2), Vector128.LessThan(left, right.V3));

        public static QuadVector128<int> CompareLessThan(QuadVector128<int> left, QuadVector128<int> right)
            => new(Vector128.LessThan(left.V0, right.V0), Vector128.LessThan(left.V1, right.V1), Vector128.LessThan(left.V2, right.V2), Vector128.LessThan(left.V3, right.V3));

        public static QuadVector128<int> CompareLessThan(QuadVector128<int> left, Vector128<int> right)
            => new(Vector128.LessThan(left.V0, right), Vector128.LessThan(left.V1, right), Vector128.LessThan(left.V2, right), Vector128.LessThan(left.V3, right));

        public static QuadVector128<int> CompareLessThan(Vector128<int> left, QuadVector128<int> right)
            => new(Vector128.LessThan(left, right.V0), Vector128.LessThan(left, right.V1), Vector128.LessThan(left, right.V2), Vector128.LessThan(left, right.V3));

        public static QuadVector128<float> CompareLessThan(QuadVector128<float> left, QuadVector128<float> right)
            => new(Vector128.LessThan(left.V0, right.V0), Vector128.LessThan(left.V1, right.V1), Vector128.LessThan(left.V2, right.V2), Vector128.LessThan(left.V3, right.V3));

        public static QuadVector128<float> CompareLessThan(QuadVector128<float> left, Vector128<float> right)
            => new(Vector128.LessThan(left.V0, right), Vector128.LessThan(left.V1, right), Vector128.LessThan(left.V2, right), Vector128.LessThan(left.V3, right));

        public static QuadVector128<float> CompareLessThan(Vector128<float> left, QuadVector128<float> right)
            => new(Vector128.LessThan(left, right.V0), Vector128.LessThan(left, right.V1), Vector128.LessThan(left, right.V2), Vector128.LessThan(left, right.V3));

        public static QuadVector128<ulong> CompareLessThan(QuadVector128<ulong> left, QuadVector128<ulong> right)
            => new(Vector128.LessThan(left.V0, right.V0), Vector128.LessThan(left.V1, right.V1), Vector128.LessThan(left.V2, right.V2), Vector128.LessThan(left.V3, right.V3));

        public static QuadVector128<ulong> CompareLessThan(QuadVector128<ulong> left, Vector128<ulong> right)
            => new(Vector128.LessThan(left.V0, right), Vector128.LessThan(left.V1, right), Vector128.LessThan(left.V2, right), Vector128.LessThan(left.V3, right));

        public static QuadVector128<ulong> CompareLessThan(Vector128<ulong> left, QuadVector128<ulong> right)
            => new(Vector128.LessThan(left, right.V0), Vector128.LessThan(left, right.V1), Vector128.LessThan(left, right.V2), Vector128.LessThan(left, right.V3));

        public static QuadVector128<long> CompareLessThan(QuadVector128<long> left, QuadVector128<long> right)
            => new(Vector128.LessThan(left.V0, right.V0), Vector128.LessThan(left.V1, right.V1), Vector128.LessThan(left.V2, right.V2), Vector128.LessThan(left.V3, right.V3));

        public static QuadVector128<long> CompareLessThan(QuadVector128<long> left, Vector128<long> right)
            => new(Vector128.LessThan(left.V0, right), Vector128.LessThan(left.V1, right), Vector128.LessThan(left.V2, right), Vector128.LessThan(left.V3, right));

        public static QuadVector128<long> CompareLessThan(Vector128<long> left, QuadVector128<long> right)
            => new(Vector128.LessThan(left, right.V0), Vector128.LessThan(left, right.V1), Vector128.LessThan(left, right.V2), Vector128.LessThan(left, right.V3));

        public static QuadVector128<double> CompareLessThan(QuadVector128<double> left, QuadVector128<double> right)
            => new(Vector128.LessThan(left.V0, right.V0), Vector128.LessThan(left.V1, right.V1), Vector128.LessThan(left.V2, right.V2), Vector128.LessThan(left.V3, right.V3));

        public static QuadVector128<double> CompareLessThan(QuadVector128<double> left, Vector128<double> right)
            => new(Vector128.LessThan(left.V0, right), Vector128.LessThan(left.V1, right), Vector128.LessThan(left.V2, right), Vector128.LessThan(left.V3, right));

        public static QuadVector128<double> CompareLessThan(Vector128<double> left, QuadVector128<double> right)
            => new(Vector128.LessThan(left, right.V0), Vector128.LessThan(left, right.V1), Vector128.LessThan(left, right.V2), Vector128.LessThan(left, right.V3));

        public static QuadVector128<byte> CompareLessThanOrEqual(QuadVector128<byte> left, QuadVector128<byte> right)
            => new(Vector128.LessThanOrEqual(left.V0, right.V0), Vector128.LessThanOrEqual(left.V1, right.V1), Vector128.LessThanOrEqual(left.V2, right.V2), Vector128.LessThanOrEqual(left.V3, right.V3));

        public static QuadVector128<byte> CompareLessThanOrEqual(QuadVector128<byte> left, Vector128<byte> right)
            => new(Vector128.LessThanOrEqual(left.V0, right), Vector128.LessThanOrEqual(left.V1, right), Vector128.LessThanOrEqual(left.V2, right), Vector128.LessThanOrEqual(left.V3, right));

        public static QuadVector128<byte> CompareLessThanOrEqual(Vector128<byte> left, QuadVector128<byte> right)
            => new(Vector128.LessThanOrEqual(left, right.V0), Vector128.LessThanOrEqual(left, right.V1), Vector128.LessThanOrEqual(left, right.V2), Vector128.LessThanOrEqual(left, right.V3));

        public static QuadVector128<sbyte> CompareLessThanOrEqual(QuadVector128<sbyte> left, QuadVector128<sbyte> right)
            => new(Vector128.LessThanOrEqual(left.V0, right.V0), Vector128.LessThanOrEqual(left.V1, right.V1), Vector128.LessThanOrEqual(left.V2, right.V2), Vector128.LessThanOrEqual(left.V3, right.V3));

        public static QuadVector128<sbyte> CompareLessThanOrEqual(QuadVector128<sbyte> left, Vector128<sbyte> right)
            => new(Vector128.LessThanOrEqual(left.V0, right), Vector128.LessThanOrEqual(left.V1, right), Vector128.LessThanOrEqual(left.V2, right), Vector128.LessThanOrEqual(left.V3, right));

        public static QuadVector128<sbyte> CompareLessThanOrEqual(Vector128<sbyte> left, QuadVector128<sbyte> right)
            => new(Vector128.LessThanOrEqual(left, right.V0), Vector128.LessThanOrEqual(left, right.V1), Vector128.LessThanOrEqual(left, right.V2), Vector128.LessThanOrEqual(left, right.V3));

        public static QuadVector128<ushort> CompareLessThanOrEqual(QuadVector128<ushort> left, QuadVector128<ushort> right)
            => new(Vector128.LessThanOrEqual(left.V0, right.V0), Vector128.LessThanOrEqual(left.V1, right.V1), Vector128.LessThanOrEqual(left.V2, right.V2), Vector128.LessThanOrEqual(left.V3, right.V3));

        public static QuadVector128<ushort> CompareLessThanOrEqual(QuadVector128<ushort> left, Vector128<ushort> right)
            => new(Vector128.LessThanOrEqual(left.V0, right), Vector128.LessThanOrEqual(left.V1, right), Vector128.LessThanOrEqual(left.V2, right), Vector128.LessThanOrEqual(left.V3, right));

        public static QuadVector128<ushort> CompareLessThanOrEqual(Vector128<ushort> left, QuadVector128<ushort> right)
            => new(Vector128.LessThanOrEqual(left, right.V0), Vector128.LessThanOrEqual(left, right.V1), Vector128.LessThanOrEqual(left, right.V2), Vector128.LessThanOrEqual(left, right.V3));

        public static QuadVector128<short> CompareLessThanOrEqual(QuadVector128<short> left, QuadVector128<short> right)
            => new(Vector128.LessThanOrEqual(left.V0, right.V0), Vector128.LessThanOrEqual(left.V1, right.V1), Vector128.LessThanOrEqual(left.V2, right.V2), Vector128.LessThanOrEqual(left.V3, right.V3));

        public static QuadVector128<short> CompareLessThanOrEqual(QuadVector128<short> left, Vector128<short> right)
            => new(Vector128.LessThanOrEqual(left.V0, right), Vector128.LessThanOrEqual(left.V1, right), Vector128.LessThanOrEqual(left.V2, right), Vector128.LessThanOrEqual(left.V3, right));

        public static QuadVector128<short> CompareLessThanOrEqual(Vector128<short> left, QuadVector128<short> right)
            => new(Vector128.LessThanOrEqual(left, right.V0), Vector128.LessThanOrEqual(left, right.V1), Vector128.LessThanOrEqual(left, right.V2), Vector128.LessThanOrEqual(left, right.V3));

        public static QuadVector128<uint> CompareLessThanOrEqual(QuadVector128<uint> left, QuadVector128<uint> right)
            => new(Vector128.LessThanOrEqual(left.V0, right.V0), Vector128.LessThanOrEqual(left.V1, right.V1), Vector128.LessThanOrEqual(left.V2, right.V2), Vector128.LessThanOrEqual(left.V3, right.V3));

        public static QuadVector128<uint> CompareLessThanOrEqual(QuadVector128<uint> left, Vector128<uint> right)
            => new(Vector128.LessThanOrEqual(left.V0, right), Vector128.LessThanOrEqual(left.V1, right), Vector128.LessThanOrEqual(left.V2, right), Vector128.LessThanOrEqual(left.V3, right));

        public static QuadVector128<uint> CompareLessThanOrEqual(Vector128<uint> left, QuadVector128<uint> right)
            => new(Vector128.LessThanOrEqual(left, right.V0), Vector128.LessThanOrEqual(left, right.V1), Vector128.LessThanOrEqual(left, right.V2), Vector128.LessThanOrEqual(left, right.V3));

        public static QuadVector128<int> CompareLessThanOrEqual(QuadVector128<int> left, QuadVector128<int> right)
            => new(Vector128.LessThanOrEqual(left.V0, right.V0), Vector128.LessThanOrEqual(left.V1, right.V1), Vector128.LessThanOrEqual(left.V2, right.V2), Vector128.LessThanOrEqual(left.V3, right.V3));

        public static QuadVector128<int> CompareLessThanOrEqual(QuadVector128<int> left, Vector128<int> right)
            => new(Vector128.LessThanOrEqual(left.V0, right), Vector128.LessThanOrEqual(left.V1, right), Vector128.LessThanOrEqual(left.V2, right), Vector128.LessThanOrEqual(left.V3, right));

        public static QuadVector128<int> CompareLessThanOrEqual(Vector128<int> left, QuadVector128<int> right)
            => new(Vector128.LessThanOrEqual(left, right.V0), Vector128.LessThanOrEqual(left, right.V1), Vector128.LessThanOrEqual(left, right.V2), Vector128.LessThanOrEqual(left, right.V3));

        public static QuadVector128<float> CompareLessThanOrEqual(QuadVector128<float> left, QuadVector128<float> right)
            => new(Vector128.LessThanOrEqual(left.V0, right.V0), Vector128.LessThanOrEqual(left.V1, right.V1), Vector128.LessThanOrEqual(left.V2, right.V2), Vector128.LessThanOrEqual(left.V3, right.V3));

        public static QuadVector128<float> CompareLessThanOrEqual(QuadVector128<float> left, Vector128<float> right)
            => new(Vector128.LessThanOrEqual(left.V0, right), Vector128.LessThanOrEqual(left.V1, right), Vector128.LessThanOrEqual(left.V2, right), Vector128.LessThanOrEqual(left.V3, right));

        public static QuadVector128<float> CompareLessThanOrEqual(Vector128<float> left, QuadVector128<float> right)
            => new(Vector128.LessThanOrEqual(left, right.V0), Vector128.LessThanOrEqual(left, right.V1), Vector128.LessThanOrEqual(left, right.V2), Vector128.LessThanOrEqual(left, right.V3));

        public static QuadVector128<ulong> CompareLessThanOrEqual(QuadVector128<ulong> left, QuadVector128<ulong> right)
            => new(Vector128.LessThanOrEqual(left.V0, right.V0), Vector128.LessThanOrEqual(left.V1, right.V1), Vector128.LessThanOrEqual(left.V2, right.V2), Vector128.LessThanOrEqual(left.V3, right.V3));

        public static QuadVector128<ulong> CompareLessThanOrEqual(QuadVector128<ulong> left, Vector128<ulong> right)
            => new(Vector128.LessThanOrEqual(left.V0, right), Vector128.LessThanOrEqual(left.V1, right), Vector128.LessThanOrEqual(left.V2, right), Vector128.LessThanOrEqual(left.V3, right));

        public static QuadVector128<ulong> CompareLessThanOrEqual(Vector128<ulong> left, QuadVector128<ulong> right)
            => new(Vector128.LessThanOrEqual(left, right.V0), Vector128.LessThanOrEqual(left, right.V1), Vector128.LessThanOrEqual(left, right.V2), Vector128.LessThanOrEqual(left, right.V3));

        public static QuadVector128<long> CompareLessThanOrEqual(QuadVector128<long> left, QuadVector128<long> right)
            => new(Vector128.LessThanOrEqual(left.V0, right.V0), Vector128.LessThanOrEqual(left.V1, right.V1), Vector128.LessThanOrEqual(left.V2, right.V2), Vector128.LessThanOrEqual(left.V3, right.V3));

        public static QuadVector128<long> CompareLessThanOrEqual(QuadVector128<long> left, Vector128<long> right)
            => new(Vector128.LessThanOrEqual(left.V0, right), Vector128.LessThanOrEqual(left.V1, right), Vector128.LessThanOrEqual(left.V2, right), Vector128.LessThanOrEqual(left.V3, right));

        public static QuadVector128<long> CompareLessThanOrEqual(Vector128<long> left, QuadVector128<long> right)
            => new(Vector128.LessThanOrEqual(left, right.V0), Vector128.LessThanOrEqual(left, right.V1), Vector128.LessThanOrEqual(left, right.V2), Vector128.LessThanOrEqual(left, right.V3));

        public static QuadVector128<double> CompareLessThanOrEqual(QuadVector128<double> left, QuadVector128<double> right)
            => new(Vector128.LessThanOrEqual(left.V0, right.V0), Vector128.LessThanOrEqual(left.V1, right.V1), Vector128.LessThanOrEqual(left.V2, right.V2), Vector128.LessThanOrEqual(left.V3, right.V3));

        public static QuadVector128<double> CompareLessThanOrEqual(QuadVector128<double> left, Vector128<double> right)
            => new(Vector128.LessThanOrEqual(left.V0, right), Vector128.LessThanOrEqual(left.V1, right), Vector128.LessThanOrEqual(left.V2, right), Vector128.LessThanOrEqual(left.V3, right));

        public static QuadVector128<double> CompareLessThanOrEqual(Vector128<double> left, QuadVector128<double> right)
            => new(Vector128.LessThanOrEqual(left, right.V0), Vector128.LessThanOrEqual(left, right.V1), Vector128.LessThanOrEqual(left, right.V2), Vector128.LessThanOrEqual(left, right.V3));

        public static QuadVector128<byte> ShiftLeftLogical(QuadVector128<byte> vector, int shiftCount)
            => new(Vector128.ShiftLeft(vector.V0, shiftCount), Vector128.ShiftLeft(vector.V1, shiftCount), Vector128.ShiftLeft(vector.V2, shiftCount), Vector128.ShiftLeft(vector.V3, shiftCount));

        public static QuadVector128<sbyte> ShiftLeftLogical(QuadVector128<sbyte> vector, int shiftCount)
            => new(Vector128.ShiftLeft(vector.V0, shiftCount), Vector128.ShiftLeft(vector.V1, shiftCount), Vector128.ShiftLeft(vector.V2, shiftCount), Vector128.ShiftLeft(vector.V3, shiftCount));

        public static QuadVector128<ushort> ShiftLeftLogical(QuadVector128<ushort> vector, int shiftCount)
            => new(Vector128.ShiftLeft(vector.V0, shiftCount), Vector128.ShiftLeft(vector.V1, shiftCount), Vector128.ShiftLeft(vector.V2, shiftCount), Vector128.ShiftLeft(vector.V3, shiftCount));

        public static QuadVector128<short> ShiftLeftLogical(QuadVector128<short> vector, int shiftCount)
            => new(Vector128.ShiftLeft(vector.V0, shiftCount), Vector128.ShiftLeft(vector.V1, shiftCount), Vector128.ShiftLeft(vector.V2, shiftCount), Vector128.ShiftLeft(vector.V3, shiftCount));

        public static QuadVector128<uint> ShiftLeftLogical(QuadVector128<uint> vector, int shiftCount)
            => new(Vector128.ShiftLeft(vector.V0, shiftCount), Vector128.ShiftLeft(vector.V1, shiftCount), Vector128.ShiftLeft(vector.V2, shiftCount), Vector128.ShiftLeft(vector.V3, shiftCount));

        public static QuadVector128<int> ShiftLeftLogical(QuadVector128<int> vector, int shiftCount)
            => new(Vector128.ShiftLeft(vector.V0, shiftCount), Vector128.ShiftLeft(vector.V1, shiftCount), Vector128.ShiftLeft(vector.V2, shiftCount), Vector128.ShiftLeft(vector.V3, shiftCount));

        public static QuadVector128<ulong> ShiftLeftLogical(QuadVector128<ulong> vector, int shiftCount)
            => new(Vector128.ShiftLeft(vector.V0, shiftCount), Vector128.ShiftLeft(vector.V1, shiftCount), Vector128.ShiftLeft(vector.V2, shiftCount), Vector128.ShiftLeft(vector.V3, shiftCount));

        public static QuadVector128<long> ShiftLeftLogical(QuadVector128<long> vector, int shiftCount)
            => new(Vector128.ShiftLeft(vector.V0, shiftCount), Vector128.ShiftLeft(vector.V1, shiftCount), Vector128.ShiftLeft(vector.V2, shiftCount), Vector128.ShiftLeft(vector.V3, shiftCount));

        public static QuadVector128<byte> ShiftRightLogical(QuadVector128<byte> vector, int shiftCount)
            => new(Vector128.ShiftRightLogical(vector.V0, shiftCount), Vector128.ShiftRightLogical(vector.V1, shiftCount), Vector128.ShiftRightLogical(vector.V2, shiftCount), Vector128.ShiftRightLogical(vector.V3, shiftCount));

        public static QuadVector128<sbyte> ShiftRightArithmetic(QuadVector128<sbyte> vector, int shiftCount)
            => new(Vector128.ShiftRightArithmetic(vector.V0, shiftCount), Vector128.ShiftRightArithmetic(vector.V1, shiftCount), Vector128.ShiftRightArithmetic(vector.V2, shiftCount), Vector128.ShiftRightArithmetic(vector.V3, shiftCount));

        public static QuadVector128<ushort> ShiftRightLogical(QuadVector128<ushort> vector, int shiftCount)
            => new(Vector128.ShiftRightLogical(vector.V0, shiftCount), Vector128.ShiftRightLogical(vector.V1, shiftCount), Vector128.ShiftRightLogical(vector.V2, shiftCount), Vector128.ShiftRightLogical(vector.V3, shiftCount));

        public static QuadVector128<short> ShiftRightArithmetic(QuadVector128<short> vector, int shiftCount)
            => new(Vector128.ShiftRightArithmetic(vector.V0, shiftCount), Vector128.ShiftRightArithmetic(vector.V1, shiftCount), Vector128.ShiftRightArithmetic(vector.V2, shiftCount), Vector128.ShiftRightArithmetic(vector.V3, shiftCount));

        public static QuadVector128<uint> ShiftRightLogical(QuadVector128<uint> vector, int shiftCount)
            => new(Vector128.ShiftRightLogical(vector.V0, shiftCount), Vector128.ShiftRightLogical(vector.V1, shiftCount), Vector128.ShiftRightLogical(vector.V2, shiftCount), Vector128.ShiftRightLogical(vector.V3, shiftCount));

        public static QuadVector128<int> ShiftRightArithmetic(QuadVector128<int> vector, int shiftCount)
            => new(Vector128.ShiftRightArithmetic(vector.V0, shiftCount), Vector128.ShiftRightArithmetic(vector.V1, shiftCount), Vector128.ShiftRightArithmetic(vector.V2, shiftCount), Vector128.ShiftRightArithmetic(vector.V3, shiftCount));

        public static QuadVector128<ulong> ShiftRightLogical(QuadVector128<ulong> vector, int shiftCount)
            => new(Vector128.ShiftRightLogical(vector.V0, shiftCount), Vector128.ShiftRightLogical(vector.V1, shiftCount), Vector128.ShiftRightLogical(vector.V2, shiftCount), Vector128.ShiftRightLogical(vector.V3, shiftCount));

        public static QuadVector128<long> ShiftRightArithmetic(QuadVector128<long> vector, int shiftCount)
            => new(Vector128.ShiftRightArithmetic(vector.V0, shiftCount), Vector128.ShiftRightArithmetic(vector.V1, shiftCount), Vector128.ShiftRightArithmetic(vector.V2, shiftCount), Vector128.ShiftRightArithmetic(vector.V3, shiftCount));

        public static QuadVector128<byte> Create(byte e0, byte e1, byte e2, byte e3, byte e4, byte e5, byte e6, byte e7, byte e8, byte e9, byte e10, byte e11, byte e12, byte e13, byte e14, byte e15, byte e16, byte e17, byte e18, byte e19, byte e20, byte e21, byte e22, byte e23, byte e24, byte e25, byte e26, byte e27, byte e28, byte e29, byte e30, byte e31, byte e32, byte e33, byte e34, byte e35, byte e36, byte e37, byte e38, byte e39, byte e40, byte e41, byte e42, byte e43, byte e44, byte e45, byte e46, byte e47, byte e48, byte e49, byte e50, byte e51, byte e52, byte e53, byte e54, byte e55, byte e56, byte e57, byte e58, byte e59, byte e60, byte e61, byte e62, byte e63)
            => new(Vector128.Create(e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15), Vector128.Create(e16, e17, e18, e19, e20, e21, e22, e23, e24, e25, e26, e27, e28, e29, e30, e31), Vector128.Create(e32, e33, e34, e35, e36, e37, e38, e39, e40, e41, e42, e43, e44, e45, e46, e47), Vector128.Create(e48, e49, e50, e51, e52, e53, e54, e55, e56, e57, e58, e59, e60, e61, e62, e63));
        
        public static QuadVector128<sbyte> Create(sbyte e0, sbyte e1, sbyte e2, sbyte e3, sbyte e4, sbyte e5, sbyte e6, sbyte e7, sbyte e8, sbyte e9, sbyte e10, sbyte e11, sbyte e12, sbyte e13, sbyte e14, sbyte e15, sbyte e16, sbyte e17, sbyte e18, sbyte e19, sbyte e20, sbyte e21, sbyte e22, sbyte e23, sbyte e24, sbyte e25, sbyte e26, sbyte e27, sbyte e28, sbyte e29, sbyte e30, sbyte e31, sbyte e32, sbyte e33, sbyte e34, sbyte e35, sbyte e36, sbyte e37, sbyte e38, sbyte e39, sbyte e40, sbyte e41, sbyte e42, sbyte e43, sbyte e44, sbyte e45, sbyte e46, sbyte e47, sbyte e48, sbyte e49, sbyte e50, sbyte e51, sbyte e52, sbyte e53, sbyte e54, sbyte e55, sbyte e56, sbyte e57, sbyte e58, sbyte e59, sbyte e60, sbyte e61, sbyte e62, sbyte e63)
            => new(Vector128.Create(e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15), Vector128.Create(e16, e17, e18, e19, e20, e21, e22, e23, e24, e25, e26, e27, e28, e29, e30, e31), Vector128.Create(e32, e33, e34, e35, e36, e37, e38, e39, e40, e41, e42, e43, e44, e45, e46, e47), Vector128.Create(e48, e49, e50, e51, e52, e53, e54, e55, e56, e57, e58, e59, e60, e61, e62, e63));
        
        public static QuadVector128<ushort> Create(ushort e0, ushort e1, ushort e2, ushort e3, ushort e4, ushort e5, ushort e6, ushort e7, ushort e8, ushort e9, ushort e10, ushort e11, ushort e12, ushort e13, ushort e14, ushort e15, ushort e16, ushort e17, ushort e18, ushort e19, ushort e20, ushort e21, ushort e22, ushort e23, ushort e24, ushort e25, ushort e26, ushort e27, ushort e28, ushort e29, ushort e30, ushort e31)
            => new(Vector128.Create(e0, e1, e2, e3, e4, e5, e6, e7), Vector128.Create(e8, e9, e10, e11, e12, e13, e14, e15), Vector128.Create(e16, e17, e18, e19, e20, e21, e22, e23), Vector128.Create(e24, e25, e26, e27, e28, e29, e30, e31));
        
        public static QuadVector128<short> Create(short e0, short e1, short e2, short e3, short e4, short e5, short e6, short e7, short e8, short e9, short e10, short e11, short e12, short e13, short e14, short e15, short e16, short e17, short e18, short e19, short e20, short e21, short e22, short e23, short e24, short e25, short e26, short e27, short e28, short e29, short e30, short e31)
            => new(Vector128.Create(e0, e1, e2, e3, e4, e5, e6, e7), Vector128.Create(e8, e9, e10, e11, e12, e13, e14, e15), Vector128.Create(e16, e17, e18, e19, e20, e21, e22, e23), Vector128.Create(e24, e25, e26, e27, e28, e29, e30, e31));
        
        public static QuadVector128<uint> Create(uint e0, uint e1, uint e2, uint e3, uint e4, uint e5, uint e6, uint e7, uint e8, uint e9, uint e10, uint e11, uint e12, uint e13, uint e14, uint e15)
            => new(Vector128.Create(e0, e1, e2, e3), Vector128.Create(e4, e5, e6, e7), Vector128.Create(e8, e9, e10, e11), Vector128.Create(e12, e13, e14, e15));
        
        public static QuadVector128<int> Create(int e0, int e1, int e2, int e3, int e4, int e5, int e6, int e7, int e8, int e9, int e10, int e11, int e12, int e13, int e14, int e15)
            => new(Vector128.Create(e0, e1, e2, e3), Vector128.Create(e4, e5, e6, e7), Vector128.Create(e8, e9, e10, e11), Vector128.Create(e12, e13, e14, e15));
        
        public static QuadVector128<float> Create(float e0, float e1, float e2, float e3, float e4, float e5, float e6, float e7, float e8, float e9, float e10, float e11, float e12, float e13, float e14, float e15)
            => new(Vector128.Create(e0, e1, e2, e3), Vector128.Create(e4, e5, e6, e7), Vector128.Create(e8, e9, e10, e11), Vector128.Create(e12, e13, e14, e15));
        
        public static QuadVector128<ulong> Create(ulong e0, ulong e1, ulong e2, ulong e3, ulong e4, ulong e5, ulong e6, ulong e7)
            => new(Vector128.Create(e0, e1), Vector128.Create(e2, e3), Vector128.Create(e4, e5), Vector128.Create(e6, e7));
        
        public static QuadVector128<long> Create(long e0, long e1, long e2, long e3, long e4, long e5, long e6, long e7)
            => new(Vector128.Create(e0, e1), Vector128.Create(e2, e3), Vector128.Create(e4, e5), Vector128.Create(e6, e7));
        
        public static QuadVector128<double> Create(double e0, double e1, double e2, double e3, double e4, double e5, double e6, double e7)
            => new(Vector128.Create(e0, e1), Vector128.Create(e2, e3), Vector128.Create(e4, e5), Vector128.Create(e6, e7));
        
        public static QuadVector128<byte> Create(byte value)
        {
            var v0_nx = Vector128.Create(value);
            return new(v0_nx, v0_nx, v0_nx, v0_nx);
        }

        public static QuadVector128<sbyte> Create(sbyte value)
        {
            var v0_nx = Vector128.Create(value);
            return new(v0_nx, v0_nx, v0_nx, v0_nx);
        }

        public static QuadVector128<ushort> Create(ushort value)
        {
            var v0_nx = Vector128.Create(value);
            return new(v0_nx, v0_nx, v0_nx, v0_nx);
        }

        public static QuadVector128<short> Create(short value)
        {
            var v0_nx = Vector128.Create(value);
            return new(v0_nx, v0_nx, v0_nx, v0_nx);
        }

        public static QuadVector128<uint> Create(uint value)
        {
            var v0_nx = Vector128.Create(value);
            return new(v0_nx, v0_nx, v0_nx, v0_nx);
        }

        public static QuadVector128<int> Create(int value)
        {
            var v0_nx = Vector128.Create(value);
            return new(v0_nx, v0_nx, v0_nx, v0_nx);
        }

        public static QuadVector128<float> Create(float value)
        {
            var v0_nx = Vector128.Create(value);
            return new(v0_nx, v0_nx, v0_nx, v0_nx);
        }

        public static QuadVector128<ulong> Create(ulong value)
        {
            var v0_nx = Vector128.Create(value);
            return new(v0_nx, v0_nx, v0_nx, v0_nx);
        }

        public static QuadVector128<long> Create(long value)
        {
            var v0_nx = Vector128.Create(value);
            return new(v0_nx, v0_nx, v0_nx, v0_nx);
        }

        public static QuadVector128<double> Create(double value)
        {
            var v0_nx = Vector128.Create(value);
            return new(v0_nx, v0_nx, v0_nx, v0_nx);
        }

        public static QuadVector128<byte> CreateScalar(byte value)
            => new(Vector128.CreateScalar(value), default, default, default);

        public static QuadVector128<sbyte> CreateScalar(sbyte value)
            => new(Vector128.CreateScalar(value), default, default, default);

        public static QuadVector128<ushort> CreateScalar(ushort value)
            => new(Vector128.CreateScalar(value), default, default, default);

        public static QuadVector128<short> CreateScalar(short value)
            => new(Vector128.CreateScalar(value), default, default, default);

        public static QuadVector128<uint> CreateScalar(uint value)
            => new(Vector128.CreateScalar(value), default, default, default);

        public static QuadVector128<int> CreateScalar(int value)
            => new(Vector128.CreateScalar(value), default, default, default);

        public static QuadVector128<float> CreateScalar(float value)
            => new(Vector128.CreateScalar(value), default, default, default);

        public static QuadVector128<ulong> CreateScalar(ulong value)
            => new(Vector128.CreateScalar(value), default, default, default);

        public static QuadVector128<long> CreateScalar(long value)
            => new(Vector128.CreateScalar(value), default, default, default);

        public static QuadVector128<double> CreateScalar(double value)
            => new(Vector128.CreateScalar(value), default, default, default);

    }
}